import os
import bpy
import platform
import subprocess
import sys
import shutil
import re

from pathlib import Path
from datetime import datetime

from . import save_translation
from .save_translation import SaveTranslation
from .. import addon_preferences
from ..utils.blend_utils import ShowMessageBox

system = platform.system()

class BaseType:
    CORVETTE = "PlayerShipBase"
    BASE = "HomePlanetBase"
    FREIGHTER = "FreighterBase"
    EXTERNAL_BASE = "ExternalPlanetBase"
    SPACESTATION_BASE = "PlayerSpaceStationBase"
    SPACE_BASE = "PlayerSpaceBase"
    
class BaseData:
    
    base_index: int
    base_name: str
    user_data: str
    galactic_address: str
    base_type: int
    parts_count: int
    save_slot = []
    
    
    def __init__(self, index = None ,base = None, ship_ownership = None):
        
        if index is None or base is None:
            return
        
        in_base_type = base[SaveTranslation.base_type][SaveTranslation.persistent_base_types]
        parts_count = len(base[SaveTranslation.objects])
        base_name = base[SaveTranslation.base_name]
        user_data = base[SaveTranslation.user_data]
        
        if len(base_name.strip()) == 0:
            base_name = "unknow_name"
            
        ship_ownership_entry = ship_ownership[user_data] if in_base_type == BaseType.CORVETTE else None
        if ship_ownership_entry is not None and in_base_type == BaseType.CORVETTE and base_name == "Default":
            base_name = ship_ownership_entry[SaveTranslation.base_name]
        
        self.base_index = index
        self.base_name = base_name
        self.user_data = user_data
        self.galactic_address = str(base[SaveTranslation.galactic_address])
        self.base_type = in_base_type
        self.parts_count = parts_count


# return save folder path for different OS versions
def get_default_save_folder():
    if system == "Windows":
        # windows
        return (Path.home()/ "AppData/Roaming/HelloGames/NMS" )
    elif system == "Darwin":
        # macOS
        return (Path.home()/ "Library/Application Support/HelloGames/NMS" )
    elif system == "Linux":
        # Proton / Steam Play
        return (Path.home() / ".steam/steam/steamapps/compatdata" )
    else:
        ShowMessageBox(message="Manually select save folder", title= "Default sve folder not found")
        return Path.home()
   
# return parth to file generated by steam that contains persona names of each account logged into system
def get_steamname_path():
    if system == "Windows": 
        # windows
        return (Path("C:/Program Files (x86)/Steam/config/loginusers.vdf"))
    elif system == "Darwin":  
        # macOS
        return ( Path.home() / "Library/Application Support/Steam/config/loginusers.vdf")
    elif system == "Linux":
        # Linux, most common Steam install location
        return ( Path.home()/ ".steam/steam/config/loginusers.vdf")
    else:
        return None
    
# extract steam persona names from loginusers.vdf file and return dic of "steam_id":"persona name"
def get_steam_names():
    # it is stored in format like ..."users: { "steam_id" {"PersonaName" "name"} }
    pattern = re.compile(
        r'"(\d+)"\s*{[^}]*"PersonaName"\s*"([^"]+)"',
        re.DOTALL
    )
    steam_names = {}
    steamname_path = get_steamname_path()
    if steamname_path.exists():
        text = steamname_path.read_text(encoding="utf-8")
        for steam_id, persona_name in pattern.findall(text):
            steam_names[str(steam_id)] = persona_name
    return steam_names

#returns list of files with valid save file names within a given folder, parameter is string
def get_hg_files_in_folder(folder):
    hg_files_list = []
    for file in Path(folder).glob("save*.hg"):
        if re.fullmatch(r"save(\d+)?\.hg", file.name):
            hg_files_list.append(file)
    return hg_files_list

#Returns all account folders
def get_accounts_list(context):
    save_folder_path = addon_preferences.get_save_folder_path()
    if not save_folder_path or not os.path.isdir(save_folder_path):
        return []

    steam_names = get_steam_names()
    accounts_list = []
    root_dir = Path(save_folder_path)
    for folder in root_dir.iterdir():
        if not folder.is_dir():
            continue
        # Steam/Gamepass account folders
        if folder.name.startswith("st_"):
            files_list = get_hg_files_in_folder(str(folder))
            account_number = folder.name[3:]
            steam_persona = steam_names.get(account_number,None)
            if files_list is not None:
                if len(files_list) > 0:
                    accounts_list.append({
                        "steam_persona" : steam_persona,
                        "folder"  : folder
                    })
    return accounts_list
    

# Returns list of save slot data that contains save name and save files lines
def get_save_slots_list(account):
    from .save_file import SaveFile
    
    # to validate correct save file name
    pattern = re.compile(r"save(\d+)\.hg")
    # store list of all hg save files
    hg_files_list = get_hg_files_in_folder(account)
    hg_files_set = set(hg_files_list)

    # interate through each save file and record their pairs
    save_slots = []
    for save_2 in hg_files_list:

        # validate name of save file, save.hg has no number and is picked up as the pair of save2.hg
        match = pattern.fullmatch(save_2.name)
        if not match:
            continue

        #extract number from name of save file
        file_number = int(match.group(1))
        if file_number %2 == 1:
            continue

        #name of linked save file
        save_1_name = "save.hg" if file_number == 2 else f"save{file_number - 1}.hg"
        save_1 = save_2.parent / save_1_name
        #check if linked save file exits in save folder or not
        if save_1 not in hg_files_set:
            continue

        # save type is "Main" for normal save and "Season" for expeditiion
        # both properties sit near the top of the save, so only the first block is usually decompressed
        try:
            properties = SaveFile(save_2).search_properties([SaveTranslation.active_context, SaveTranslation.save_name])
        except Exception:
            continue
        save_type = properties[SaveTranslation.active_context]
        if save_type is None:
            continue

        #slot number is always half of second save file's number
        save_slot_number = file_number//2
        #links to save files for this slot
        saves_links = [str(save_1), str(save_2)]
        save_name = properties[SaveTranslation.save_name] if save_type == "Main" else "Expedition"

        save_slot = {
            "slot": save_slot_number,
            "saves": saves_links,
            "save_name": save_name or "Un-named"
        }
        save_slots.append(save_slot)
        
    #sort list according to slot number
    save_slots.sort(key=lambda x: x["slot"])
    return save_slots  

# returns list of data related to bses present in a save slot
def extract_bases_list_from_save(save_slot):
    save_file = get_save_file(save_slot)
    data = save_file.load()
    
    obfuscated_persistent_base_data = save_file.get_bases_list_pointer()
    ship_ownsership = save_file.get_ship_ownership_pointer()
    freighter_name = save_file.get_freighter_name()
    
    bases = []
    corvettes = []
    external = []
    freighter = None
    
    space = []
    space_station = []
    
    total_parts_count = 0
    
    #record only what is necessary rather than entire data about base
    for index,base in enumerate(obfuscated_persistent_base_data):
        
        base_data = BaseData(index, base, ship_ownsership)
        base_data.save_slot = save_slot
        
        #store list of corvettes and bases in their respective list
        match base_data.base_type :
            case BaseType.CORVETTE:
                corvettes.append(base_data)
            case BaseType.BASE:
                bases.append(base_data)
            case BaseType.FREIGHTER:
                base_data.base_name = freighter_name
                freighter = base_data
            case BaseType.EXTERNAL_BASE:
                if base_data.parts_count > 0:
                    external.append(base_data)
            case BaseType.SPACE_BASE:
                space.append(base_data)
            case BaseType.SPACESTATION_BASE:
                space_station.append(base_data)
        
        if base_data.base_type != BaseType.EXTERNAL_BASE:
            total_parts_count += base_data.parts_count
    
    # sort list of corvettes with restpect to their user_data, because user_data represents location of corvette in ship slots making it wasy to read
    corvettes.sort(key=lambda x: x.user_data)
    
    # return combined list in an object for easy search
    return {
        "corvettes":corvettes,
        "bases":bases,
        "external":external,
        "freighter": freighter,
        "space":space + space_station,
        "spacestation":space_station,
        "total_parts_count": total_parts_count,
    }
    
    
# active save is most recently modified save file
def get_lastes_save_file_location(save_slot):
    save_1 = Path(save_slot[0])
    save_2 = Path(save_slot[1])
    
    # store when last time these save files were modified
    m_time_save_1 = os.path.getmtime(save_1)
    m_time_save_2 = os.path.getmtime(save_2)
    
    # return the save file that was most recently modified
    return save_1 if m_time_save_1 > m_time_save_2 else save_2
    
# helper function that gives returns save file object for easier loading
def get_save_file(save_slot):
    save_location = get_lastes_save_file_location(save_slot)
    from .save_file import SaveFile
    save_file = SaveFile(save_location)
    return save_file


# impart a base from save file
def import_paticular_base_from_save(base_identifier,  save_slot):
    save_file = get_save_file(save_slot)
    save_file.load()
    
    # fist see if base actially exists or not
    searched_base = save_file.search_base_with_identifier(base_identifier)
    if searched_base is None:
        message = (
            "Error importing base"
        )
        ShowMessageBox(message = message, title="Export Failed", icon = "WARNING_LARGE")
        return None
        
    #return bases after translating it to engish
    searched_base = save_translation.translate_to_eng_data(searched_base)

    return searched_base
    
# error with its cause, for messages shown to the user
# file errors drop their full paths, the message already names the file
def describe_error(error):
    if isinstance(error, OSError) and error.strerror:
        return f"{type(error).__name__}: {error.strerror}"
    return f"{type(error).__name__}: {error}"

#save a base to save file
# the newest save file is the one the game loads, so it must contain the base, the older one is updated too when it has it
# both files are prepared and backed up before anything is written, and the older file is written first so the newest stays newest
# returns (success, message)
def save_base_to_save_file(objects_data, base_identifier,  save_slot, base_name = None):
    from .save_file import SaveFile, write_file_atomic

    newest = get_lastes_save_file_location(save_slot)
    ordered_paths = [Path(p) for p in save_slot if Path(p) != newest] + [newest]
    obf_objects = save_translation.translate_to_obf_data(objects_data)

    # load, update and compress each file in memory, nothing is written yet
    prepared = []
    skipped = []
    for path in ordered_paths:
        is_newest = path == newest
        try:
            save_file = SaveFile(path)
            save_file.load()

            # look for base in save file to see it it exist or not
            in_base = save_file.search_base_with_identifier(base_identifier)
            if in_base is None:
                if is_newest:
                    return False, (
                        f"Export failed: base not found in {path.name}, the newest save file. "
                        "Nothing was written, repinning the base may resolve this issue"
                    )
                skipped.append(f"{path.name} (base not found)")
                continue

            # here update objects list with list provided
            in_base[SaveTranslation.objects] = obf_objects

            # update name of base if provided
            if base_name is not None:
                # update name in PersistentPlayerBases
                in_base[SaveTranslation.base_name] = base_name

                # update name in ship_ownsership
                userdata = base_identifier["user_data"]
                ship_ownsership_element = save_file.get_ship_ownsership_element(userdata)
                ship_ownsership_element[SaveTranslation.base_name] = base_name

            prepared.append((path, save_file.pack()))
        except Exception as error:
            if is_newest:
                return False, f"Export failed preparing {path.name}: {describe_error(error)}. Nothing was written"
            skipped.append(f"{path.name} ({describe_error(error)})")

    # back up every file before the first write
    backups = {}
    for path, _ in prepared:
        try:
            backups[path] = SaveFile(path).make_backup()
        except Exception as error:
            return False, f"Export failed backing up {path.name}: {describe_error(error)}. Nothing was written"

    # write, and put back files already written if a later one fails, so the slot is never left half exported
    written = []
    for path, data in prepared:
        try:
            write_file_atomic(path, data)
        except Exception as error:
            message = f"Export failed writing {path.name}: {describe_error(error)}. "
            return False, message + restore_from_backups(written, backups)
        written.append(path)

    message = "Base/Corvette saved sucessfully to " + " and ".join(path.name for path, _ in reversed(prepared))
    if skipped:
        message += ", skipped " + ", ".join(skipped)
    return True, message

# put written save files back from their backups, keeping their original modified times so the newest file stays newest
# returns a sentence describing what happened, for the export message
def restore_from_backups(written, backups):
    from .save_file import write_file_atomic

    if not written:
        return "Nothing was written"

    failed = []
    for path in written:
        try:
            backup = Path(backups[path])
            write_file_atomic(path, backup.read_bytes())
            shutil.copystat(backup, path)
        except Exception as error:
            failed.append(f"{path.name} ({describe_error(error)})")

    if failed:
        return (
            "Restoring from backup also failed for " + ", ".join(failed)
            + ", copy them back by hand from the blender_backup folder"
        )
    return ", ".join(path.name for path in written) + " restored from backup"

# a folder within save_directory , where backups will be stored
def get_backups_folder(save_links):
    folder = os.path.dirname(save_links[0])
    backup_folder = os.path.join(
        folder,"nms_base_builder_backup",
    )
    #create backup folder if it doesnt exist
    os.makedirs(backup_folder, exist_ok=True)
    return backup_folder

# make backup of both save files linked to a save slot
def backup_save_files(save_links):
    backup_folder = get_backups_folder(save_links)
    # add date and time in bakcup file's name to make make manual searching easier
    dat_and_time = datetime.now().strftime("d-%Y-%m-%d_t-%H-%M-%S-%f")[:-3]
    
    
    save_1 = save_links[0]
    save_2 = save_links[1]
    s1_name, s1_ext = os.path.splitext(os.path.basename(save_1))
    s2_name, s2_ext = os.path.splitext(os.path.basename(save_2))
    
    save_1_backup = os.path.join(
        backup_folder,
        f"{s1_name}{s1_ext}.{dat_and_time}.blender.bak"
    )
    save_2_backup = os.path.join(
        backup_folder,
        f"{s2_name}{s2_ext}.{dat_and_time}.blender.bak"
    )
    
    #make exact copies of those sace files and just change names
    shutil.copy2(save_1, save_1_backup)
    shutil.copy2(save_2, save_2_backup)
    
# Open backup for each OS type
def open_backup_folder_in_explorer(save_links):
    backup_folder = Path(get_backups_folder(save_links))

    if not backup_folder.exists():
        print(f"Folder does not exist: {backup_folder}")
        return

    if sys.platform == "win32": #windows
        os.startfile(backup_folder)
    elif sys.platform == "darwin":  # macOS
        subprocess.Popen(["open", str(backup_folder)])
    else:  # Linux
        subprocess.Popen(["xdg-open", str(backup_folder)])
    
# Check if a path string is valid NMS save folder or not
def validate_save_folder(save_folder):
    save_folder = Path(save_folder)
    return save_folder.parts[-2:] == ("HelloGames", "NMS")
    
    
